package protocol

import "strings"

const (
	ReplyTag  = "+airc/reply-to"
	ThreadTag = "+airc/thread"
)

// ValidMessageID accepts the canonical IDs generated by aircd.
func ValidMessageID(id string) bool {
	if len(id) != 32 {
		return false
	}
	for _, c := range id {
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			return false
		}
	}
	return true
}

// ConversationTarget recognizes history/observation selectors. A thread
// includes its root and descendants; replies selects only immediate replies.
func ConversationTarget(target string) (id string, replies bool, ok bool) {
	if id, found := strings.CutPrefix(target, "thread:"); found {
		return id, false, ValidMessageID(id)
	}
	id, found := strings.CutPrefix(target, "replies:")
	return id, true, found && ValidMessageID(id)
}
